### ISSUE TITLE
Docs mistake for plugin name

### ISSUE THREAD

**Issue by richburdon** [GFG/serverless-apigateway-plugin#5]
Docs say
  - "serverless-apigw-plugin"

Should say:
  - "serverless-apigateway-plugin"

**Comment by duynguyenhoang** [comment]
Hi @richburdon 
https://www.npmjs.com/package/serverless-apigateway-plugin was retired, and it was moved to https://www.npmjs.com/package/serverless-apigw-plugin

CC: @Nedvedyy

**Comment by Nedvedyy** [comment]
Tks for pointing it out. @richburdon 

@luannm can u fix the typo?

**Comment by luannm** [comment]
Just updated the document. Going to close this issue.
